
WRITE_READ_FLAG = True
ERROR_FILTER = True
CROSS_BOUNDARY_FLAG = True
ONLY_DELETE = True

SONAR_EVENT_MARK = "[SONAR-EVENT]"
SONAR_SIDE_EFFECT_MARK = "[SONAR-SIDE-EFFECT]"
SONAR_CACHE_READ_MARK = "[SONAR-CACHE-READ]"
SONAR_START_RECONCILE_MARK = "[SONAR-START-RECONCILE]"
SONAR_FINISH_RECONCILE_MARK = "[SONAR-FINISH-RECONCILE]"
SONAR_EVENT_APPLIED_MARK = "[SONAR-EVENT-APPLIED]"

POD = "pod"
PVC = "persistentvolumeclaim"
DEPLOYMENT = "deployment"
STS = "statefulset"

KTYPES = [POD, PVC, DEPLOYMENT, STS]
