---
USER: "ubuntu"
DOCKER_DEPS:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
DOCKER_TOOLS:
  - docker-ce
  - docker-ce-cli
  - containerd.io
PYTHON_PACKAGES:
  - kubernetes
  - docker
  - pyyaml
  - py-cui
  - deepdiff
