name: Kind Image Build
on:
  workflow_dispatch:
    inputs:
      platform-os:
        description: 'The platform to build the image on'
        default: 'ubuntu-latest'
        required: false
        type: choice
        options:
          - 'ubuntu-latest'
          - 'macos-latest'
  # schedule:
  #   - cron: '0 5 * * *'
env:
  IMAGE_NAMESPACE: ghcr.io/sieve-project/action
jobs:
  build:
    runs-on: ${{ inputs.platform-os }}

    steps:
      - name: Set up environment variables
        run: |
             if [ "$RUNNER_OS" == "Linux" ]; then
               echo "GOPATH=/home/runner/go" >> "$GITHUB_ENV"
             else
               echo "GOPATH=/Users/runner/go" >> "$GITHUB_ENV"
             fi
      - uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.19
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.7
      - name: Setup docker (missing in macOS)
        if: runner.os == 'macos'
        uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
      - name: Install missing tools in macOS
        if: runner.os == 'macos'
        run: |
              brew install bash kind
              `brew --prefix bash`/bin/bash # building k8s in macOS needs newer bash version
      - name: Setup GitHub Package Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
      - name: Install Python Packages
        run: |
          pip install kubernetes
          pip install pyyaml
      - name: Build Image for v1.18
        run: |
          python3 build.py -m vanilla -p -r $IMAGE_NAMESPACE
          python3 build.py -m learn -p -r $IMAGE_NAMESPACE
          python3 build.py -m test -p -r $IMAGE_NAMESPACE
          docker system prune -af
      # - name: Build Image for v1.23
      #   run: |
      #     python3 build.py -v v1.23.16 -m vanilla -p -r $IMAGE_NAMESPACE
      #     python3 build.py -v v1.23.16 -m learn -p -r $IMAGE_NAMESPACE
      #     python3 build.py -v v1.23.16 -m test -p -r $IMAGE_NAMESPACE
      #     docker system prune -af
      - name: Build Image for v1.24
        run: |
          python3 build.py -v v1.24.10 -m vanilla -p -r $IMAGE_NAMESPACE
          python3 build.py -v v1.24.10 -m learn -p -r $IMAGE_NAMESPACE
          python3 build.py -v v1.24.10 -m test -p -r $IMAGE_NAMESPACE
          docker system prune -af
