name: Kind Image Build
'on':
  workflow_dispatch: null
  # schedule:
  #   - cron: '0 5 * * *'
env:
  IMAGE_NAMESPACE: ghcr.io/sieve-project/action
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.15
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.7
      - name: Setup GitHub Package Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
      - name: Install Python Packages
        run: |
          pip install kubernetes
          pip install pyyaml
      - name: Build Image
        run: |
          python3 build.py -m vanilla -p -r $IMAGE_NAMESPACE
          python3 build.py -m learn -p -r $IMAGE_NAMESPACE
          python3 build.py -m test -p -r $IMAGE_NAMESPACE
